In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.cm import rainbow

import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [86]:
dataset = pd.read_csv('healthcare-dataset-stroke-data(3).csv')

In [87]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5000 non-null   int64  
 1   gender             5000 non-null   object 
 2   age                5000 non-null   float64
 3   hypertension       5000 non-null   int64  
 4   heart_disease      5000 non-null   int64  
 5   ever_married       5000 non-null   object 
 6   work_type          5000 non-null   object 
 7   Residence_type     5000 non-null   object 
 8   avg_glucose_level  5000 non-null   float64
 9   bmi                4425 non-null   float64
 10  smoking_status     5000 non-null   object 
 11  stroke             5000 non-null   int64  
 12  Heart Rate         5000 non-null   int64  
 13  SpO2               5000 non-null   int64  
dtypes: float64(3), int64(6), object(5)
memory usage: 547.0+ KB


In [88]:
dataset

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Heart Rate,SpO2
0,51314,Female,78.0,0,0,Yes,Private,Urban,106.74,33.0,formerly smoked,1,75,94
1,33175,Female,57.0,0,0,Yes,Govt_job,Urban,110.52,28.5,Unknown,1,96,91
2,66638,Female,68.0,1,0,No,Self-employed,Urban,79.79,29.7,never smoked,1,60,98
3,49130,Male,74.0,0,0,Yes,Private,Urban,98.55,25.6,Unknown,1,94,98
4,8154,Male,57.0,1,0,Yes,Govt_job,Urban,78.92,27.7,formerly smoked,1,67,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,30116,Female,57.0,0,0,Yes,Private,Rural,102.28,25.5,never smoked,0,66,99
4996,19773,Female,52.0,0,0,Yes,Private,Rural,96.59,26.4,never smoked,1,84,99
4997,72081,Female,57.0,1,0,Yes,Govt_job,Rural,67.41,32.9,never smoked,1,70,95
4998,46688,Female,44.0,0,0,No,Private,Urban,127.21,29.8,smokes,0,90,91


In [89]:
#dataset=dataset.replace(to_replace='?',value='0')

In [90]:
print('Finding missing values')
print(dataset.isnull().sum())

Finding missing values
id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  575
smoking_status         0
stroke                 0
Heart Rate             0
SpO2                   0
dtype: int64


In [91]:
#dataset['id']=dataset['id'].dataset(dataset['id'].mean())
dataset['bmi']=dataset['bmi'].fillna(dataset['bmi'].mean()) 
#dataset

In [92]:
print('Finding missing values')
print(dataset.isnull().sum())

Finding missing values
id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
Heart Rate           0
SpO2                 0
dtype: int64


In [93]:
dataset = dataset.dropna()
dataset

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Heart Rate,SpO2
0,51314,Female,78.0,0,0,Yes,Private,Urban,106.74,33.0,formerly smoked,1,75,94
1,33175,Female,57.0,0,0,Yes,Govt_job,Urban,110.52,28.5,Unknown,1,96,91
2,66638,Female,68.0,1,0,No,Self-employed,Urban,79.79,29.7,never smoked,1,60,98
3,49130,Male,74.0,0,0,Yes,Private,Urban,98.55,25.6,Unknown,1,94,98
4,8154,Male,57.0,1,0,Yes,Govt_job,Urban,78.92,27.7,formerly smoked,1,67,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,30116,Female,57.0,0,0,Yes,Private,Rural,102.28,25.5,never smoked,0,66,99
4996,19773,Female,52.0,0,0,Yes,Private,Rural,96.59,26.4,never smoked,1,84,99
4997,72081,Female,57.0,1,0,Yes,Govt_job,Rural,67.41,32.9,never smoked,1,70,95
4998,46688,Female,44.0,0,0,No,Private,Urban,127.21,29.8,smokes,0,90,91


In [94]:
from sklearn.preprocessing import LabelEncoder

labelencoder_X = LabelEncoder()

dataset['gender'] = labelencoder_X.fit_transform(dataset['gender'])
dataset['ever_married'] = labelencoder_X.fit_transform(dataset['ever_married'])
dataset['work_type'] = labelencoder_X.fit_transform(dataset['work_type'])
dataset['Residence_type'] = labelencoder_X.fit_transform(dataset['Residence_type'])
dataset['smoking_status'] = labelencoder_X.fit_transform(dataset['smoking_status'])



In [95]:
dataset

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,Heart Rate,SpO2
0,51314,0,78.0,0,0,1,2,1,106.74,33.0,1,1,75,94
1,33175,0,57.0,0,0,1,0,1,110.52,28.5,0,1,96,91
2,66638,0,68.0,1,0,0,3,1,79.79,29.7,2,1,60,98
3,49130,1,74.0,0,0,1,2,1,98.55,25.6,0,1,94,98
4,8154,1,57.0,1,0,1,0,1,78.92,27.7,1,1,67,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,30116,0,57.0,0,0,1,2,0,102.28,25.5,2,0,66,99
4996,19773,0,52.0,0,0,1,2,0,96.59,26.4,2,1,84,99
4997,72081,0,57.0,1,0,1,0,0,67.41,32.9,2,1,70,95
4998,46688,0,44.0,0,0,0,2,1,127.21,29.8,3,0,90,91


In [96]:
y = dataset['stroke']
X = dataset.drop(['stroke'], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35, random_state = 0)

In [97]:
gnb = GaussianNB()

In [98]:
#Train the model using the training sets
gnb.fit(X_train, y_train)

GaussianNB()

In [99]:
X_test

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,Heart Rate,SpO2
398,64523,1,54.0,1,0,1,2,1,89.93,32.100000,2,96,95
3833,32503,0,80.0,0,0,1,3,1,76.57,34.100000,2,92,93
4836,42072,0,50.0,1,0,1,2,0,73.18,30.300000,1,99,91
4572,11933,0,79.0,0,0,1,2,0,169.67,29.676475,0,84,94
636,39912,0,32.0,0,0,1,2,0,76.13,29.900000,3,91,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,54574,0,20.0,0,0,0,2,1,115.69,29.200000,2,95,91
1941,29552,0,55.0,1,1,1,2,1,210.40,40.000000,3,100,100
4882,45277,0,74.0,0,0,1,2,0,231.61,34.600000,1,82,95
1984,43717,1,57.0,1,0,1,2,1,212.08,44.200000,3,62,96


In [100]:
#Predict the response for test dataset
y_pred = gnb.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Stroke
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  normal
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  normal
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  normal
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  normal
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Str

In [101]:
print(confusion_matrix(y_test,y_pred))

[[ 352  248]
 [  85 1065]]


In [102]:
from sklearn import metrics
print("Accuracy for Naive Bayes Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for Naive Bayes Classifier : 80.97142857142858%


In [103]:
from sklearn.svm import SVC

In [104]:
#svclassifier = SVC(kernel='linear')
svclassifier = SVC()
svclassifier.fit(X_train, y_train)

SVC()

In [105]:
y_pred = svclassifier.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Stroke
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  Stroke
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  Stroke
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  Stroke
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  Stroke
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  Stroke
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  Stroke
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  Stroke
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Str

In [106]:
print(confusion_matrix(y_test,y_pred))
#print(classification_report(y_test,y_pred))

[[   0  600]
 [   0 1150]]


In [107]:
print("Accuracy for SVM Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for SVM Classifier : 65.71428571428571%


In [108]:
from sklearn import linear_model

In [109]:
logr = linear_model.LogisticRegression()
logr.fit(X_train, y_train)

LogisticRegression()

In [110]:
y_pred = logr.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Stroke
Test data  1  is  Stroke
Test data  2  is  normal
Test data  3  is  Stroke
Test data  4  is  normal
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  normal
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  normal
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  normal
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Str

In [111]:
print(confusion_matrix(y_test,y_pred))

[[ 354  246]
 [  97 1053]]


In [112]:
print("Accuracy for Logistic Regression : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for Logistic Regression : 80.4%


In [113]:
from sklearn.neighbors import KNeighborsClassifier

In [114]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [115]:
y_pred = knn.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  Stroke
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  Stroke
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  Stroke
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  Stroke
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  Stroke
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Str

In [116]:
print(confusion_matrix(y_test,y_pred))

[[ 328  272]
 [  17 1133]]


In [117]:
print("Accuracy for KNN Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for KNN Classifier : 83.48571428571428%


In [118]:
SGD = GradientBoostingClassifier(learning_rate=0.1)
SGD.fit(X_train, y_train)

GradientBoostingClassifier()

In [119]:
y_pred = SGD.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  normal
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  Stroke
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  normal
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  Stroke
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  Stroke
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  Stroke
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Str

In [120]:
print(confusion_matrix(y_test,y_pred))

[[ 421  179]
 [  20 1130]]


In [121]:
print("Accuracy for SGD Classifier : {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for SGD Classifier : 88.62857142857142%


In [122]:
dt_classifier = DecisionTreeClassifier(max_features = i, random_state = 0)
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(max_features=1749, random_state=0)

In [123]:
y_pred = dt_classifier.predict(X_test)
for i in range(0, len(y_pred)):
    i2=str(i)
    res=''
    if y_pred[i]==0:
        res='normal'
    elif y_pred[i]==1:
        res='Stroke'
    print('Test data ',i2 , ' is ',res)

Test data  0  is  normal
Test data  1  is  Stroke
Test data  2  is  Stroke
Test data  3  is  Stroke
Test data  4  is  Stroke
Test data  5  is  Stroke
Test data  6  is  Stroke
Test data  7  is  Stroke
Test data  8  is  Stroke
Test data  9  is  normal
Test data  10  is  Stroke
Test data  11  is  Stroke
Test data  12  is  Stroke
Test data  13  is  Stroke
Test data  14  is  Stroke
Test data  15  is  Stroke
Test data  16  is  normal
Test data  17  is  normal
Test data  18  is  Stroke
Test data  19  is  Stroke
Test data  20  is  Stroke
Test data  21  is  Stroke
Test data  22  is  Stroke
Test data  23  is  Stroke
Test data  24  is  Stroke
Test data  25  is  Stroke
Test data  26  is  Stroke
Test data  27  is  Stroke
Test data  28  is  Stroke
Test data  29  is  Stroke
Test data  30  is  normal
Test data  31  is  Stroke
Test data  32  is  Stroke
Test data  33  is  Stroke
Test data  34  is  Stroke
Test data  35  is  normal
Test data  36  is  Stroke
Test data  37  is  Stroke
Test data  38  is  Str

In [124]:
print(confusion_matrix(y_test,y_pred))

[[ 528   72]
 [   0 1150]]


In [125]:
print("Accuracy for Decision Tree Classifier is {}%".format(metrics.accuracy_score(y_test, y_pred)*100))

Accuracy for Decision Tree Classifier is 95.88571428571429%


In [126]:
# Naive Bayes example
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

# Now add this:
print("Naive Bayes Results:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=['Normal', 'Stroke']))


Naive Bayes Results:
[[ 352  248]
 [  85 1065]]
              precision    recall  f1-score   support

      Normal       0.81      0.59      0.68       600
      Stroke       0.81      0.93      0.86      1150

    accuracy                           0.81      1750
   macro avg       0.81      0.76      0.77      1750
weighted avg       0.81      0.81      0.80      1750



In [127]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Create and train the model
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Print results
print("K-Nearest Neighbors (KNN) Results:")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['Normal', 'Stroke']))


K-Nearest Neighbors (KNN) Results:

Confusion Matrix:
[[ 328  272]
 [  17 1133]]

Classification Report:
              precision    recall  f1-score   support

      Normal       0.95      0.55      0.69       600
      Stroke       0.81      0.99      0.89      1150

    accuracy                           0.83      1750
   macro avg       0.88      0.77      0.79      1750
weighted avg       0.86      0.83      0.82      1750

